import * as XLSX from "xlsx";
import { GROUP_LABELS, type CategoryGroupKey } from "@/lib/categories";

export type ImportedEntryRow = {
  year: number;
  month: number;
  group: CategoryGroupKey;
  category: string;
  amount: number;
  note?: string;
};

export type ImportedBalanceRow = {
  year: number;
  month: number;
  startingBalance: number;
};

export type ImportResult = {
  entries: ImportedEntryRow[];
  balances: ImportedBalanceRow[];
  errors: string[];
};

const GROUP_KEY_BY_LABEL: Record<string, CategoryGroupKey> = {};
for (const [key, label] of Object.entries(GROUP_LABELS)) {
  GROUP_KEY_BY_LABEL[label.toLowerCase()] = key as CategoryGroupKey;
  GROUP_KEY_BY_LABEL[key.toLowerCase()] = key as CategoryGroupKey;
}

function normalizeGroup(raw: unknown): CategoryGroupKey | null {
  if (typeof raw !== "string") return null;
  return GROUP_KEY_BY_LABEL[raw.trim().toLowerCase()] ?? null;
}

function toNumber(raw: unknown): number | null {
  if (typeof raw === "number") return raw;
  if (typeof raw === "string") {
    const cleaned = raw.replace(/\s/g, "").replace(",", ".").replace(/[^\d.-]/g, "");
    const n = parseFloat(cleaned);
    return Number.isNaN(n) ? null : n;
  }
  return null;
}

/**
 * Parses an uploaded workbook with two expected sheets:
 *  - "Entries": Année | Mois | Groupe | Catégorie | Montant | Note
 *  - "StartingBalance" (optional): Année | Mois | Solde de départ
 * A matching export template is generated by `buildTemplateWorkbook`.
 */
export function parseImportWorkbook(buffer: ArrayBuffer | Buffer): ImportResult {
  const workbook = XLSX.read(buffer, { type: "buffer" });
  const errors: string[] = [];
  const entries: ImportedEntryRow[] = [];
  const balances: ImportedBalanceRow[] = [];

  const entriesSheet = workbook.Sheets["Entries"] ?? workbook.Sheets[workbook.SheetNames[0]];
  if (!entriesSheet) {
    errors.push('Aucune feuille "Entries" trouvée dans le fichier.');
    return { entries, balances, errors };
  }

  const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(entriesSheet, {
    defval: null,
  });

  rows.forEach((row, i) => {
    const rowNum = i + 2; // header is row 1
    const year = toNumber(row["Année"] ?? row["Year"]);
    const month = toNumber(row["Mois"] ?? row["Month"]);
    const group = normalizeGroup(row["Groupe"] ?? row["Group"]);
    const category = String(row["Catégorie"] ?? row["Category"] ?? "").trim();
    const amount = toNumber(row["Montant"] ?? row["Amount"]);
    const note = row["Note"] ? String(row["Note"]) : undefined;

    if (!year || !month || month < 1 || month > 12) {
      errors.push(`Ligne ${rowNum}: année/mois invalide, ligne ignorée.`);
      return;
    }
    if (!group) {
      errors.push(
        `Ligne ${rowNum}: groupe "${row["Groupe"]}" non reconnu (attendu: Revenus, Dépenses fixes, Dépenses variables, Épargne).`
      );
      return;
    }
    if (!category) {
      errors.push(`Ligne ${rowNum}: catégorie manquante, ligne ignorée.`);
      return;
    }
    if (amount === null) {
      errors.push(`Ligne ${rowNum}: montant invalide, ligne ignorée.`);
      return;
    }

    entries.push({ year, month, group, category, amount, note });
  });

  const balanceSheet = workbook.Sheets["StartingBalance"];
  if (balanceSheet) {
    const balanceRows = XLSX.utils.sheet_to_json<Record<string, unknown>>(balanceSheet, {
      defval: null,
    });
    balanceRows.forEach((row, i) => {
      const rowNum = i + 2;
      const year = toNumber(row["Année"] ?? row["Year"]);
      const month = toNumber(row["Mois"] ?? row["Month"]);
      const startingBalance = toNumber(
        row["Solde de départ"] ?? row["StartingBalance"]
      );
      if (!year || !month || startingBalance === null) {
        errors.push(`StartingBalance ligne ${rowNum}: valeurs invalides, ignorée.`);
        return;
      }
      balances.push({ year, month, startingBalance });
    });
  }

  return { entries, balances, errors };
}

/** Blank template matching the import format, pre-filled with the user's current categories. */
export function buildTemplateWorkbook(
  categories: { group: CategoryGroupKey; name: string }[]
): Buffer {
  const header = ["Année", "Mois", "Groupe", "Catégorie", "Montant", "Note"];
  const year = new Date().getFullYear();
  const rows = categories.map((c) => [year, 1, GROUP_LABELS[c.group], c.name, "", ""]);

  const entriesSheet = XLSX.utils.aoa_to_sheet([header, ...rows]);
  const balanceSheet = XLSX.utils.aoa_to_sheet([
    ["Année", "Mois", "Solde de départ"],
    [year, 1, ""],
  ]);

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, entriesSheet, "Entries");
  XLSX.utils.book_append_sheet(workbook, balanceSheet, "StartingBalance");

  return XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

/** Full export of existing entries, in the same format so it can be re-imported. */
export function buildExportWorkbook(
  entries: {
    year: number;
    month: number;
    group: CategoryGroupKey;
    category: string;
    amount: number;
    note?: string | null;
  }[],
  balances: { year: number; month: number; startingBalance: number }[]
): Buffer {
  const entriesHeader = ["Année", "Mois", "Groupe", "Catégorie", "Montant", "Note"];
  const entriesRows = entries.map((e) => [
    e.year,
    e.month,
    GROUP_LABELS[e.group],
    e.category,
    e.amount,
    e.note ?? "",
  ]);
  const balanceHeader = ["Année", "Mois", "Solde de départ"];
  const balanceRows = balances.map((b) => [b.year, b.month, b.startingBalance]);

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    workbook,
    XLSX.utils.aoa_to_sheet([entriesHeader, ...entriesRows]),
    "Entries"
  );
  XLSX.utils.book_append_sheet(
    workbook,
    XLSX.utils.aoa_to_sheet([balanceHeader, ...balanceRows]),
    "StartingBalance"
  );

  return XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer;
}
